
language: ruby
rvm: 2.6.5

dist: trusty

before_install:
- yes | gem update --system --force
- gem install bundler

addons:
  postgresql: 9.6
  chrome: stable



after_success:
- CI=true TRAVIS=true coveralls --verbose