
language: ruby
rvm: 2.6.5

before_install:
  - yes | gem update --system --force
  - gem install bundler

addons:
  postgresql: 9.6
  chrome: stable

script:
  - "bundle install"
  — "rails db:create"
  — "rails db:migrate"
  — "rspec"

after_success:
- CI=true TRAVIS=true coveralls --verbose