
language: ruby
rvm: 2.6.5

dist: trusty

before_install:
- gem update bundler

addons:
  postgresql: 9.6
  chrome: stable

script:
— bundle install
— bundle exec rake db:create
— bundle exec rake db:migrate
— bundle exec rspec

after_success:
- CI=true TRAVIS=true coveralls --verbose