language: ruby

sudo: false

cache: bundler

ruby:
  - 2.6
  - ruby-head


script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
